services:
  momentum_db:
    image: mongo:latest
    container_name: momentum_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db


  frontend:
    build:
      context: ./momentum-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./momentum-frontend:/app
      - /app/node_modules
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000
    depends_on:
      - backend

  backend:
    build:
      context: ./momentum-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./momentum-backend:/app
      - /app/node_modules
    command: ["npx", "nodemon", "--watch", "./src", "--ext", "js,ts,json", "--exec", "npx ts-node ./src/index.ts"]
    environment:
      NODE_ENV: development

volumes:
  mongo_data: