services:
  momentum_db:
    image: mongo:latest
    container_name: momentum_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    networks:
      - momentum-network


  frontend:
    build:
      context: ./momentum-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./momentum-frontend:/app
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000
      NEXT_PUBLIC_DOCKER_API_URL: http://backend:5000
    depends_on:
      - backend
    networks:
      - momentum-network


  backend:
    build:
      context: ./momentum-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./momentum-backend:/app
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://root:example@momentum_db:27017
    depends_on:
      - momentum_db
    networks:
      - momentum-network
    env_file:
      - ./momentum-backend/.env

volumes:
  mongo_data:

networks:
  momentum-network:
    driver: bridge