services:
  frontend:
    build:
      context: ./momentum-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./momentum-frontend:/app
      - /app/node_modules
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000
    depends_on:
      - backend

  backend:
    build:
      context: ./momentum-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./momentum-backend:/app
      - /app/node_modules
      - /app/dist
    environment:
      NODE_ENV: development
